import numpy as np
import shap


# ---------------------------------------------------------
# Create SHAP explainer
# ---------------------------------------------------------

def create_explainer(model):
    """
    Create a SHAP TreeExplainer for the trained XGBoost model.
    """

    return shap.TreeExplainer(model)


# ---------------------------------------------------------
# Generate SHAP explanation
# ---------------------------------------------------------

def explain_prediction(
    explainer,
    processed_data,
    feature_names,
    original_patient_data,
    top_n: int = 5,
):
    """
    Generate the top SHAP contributors for one patient.

    Parameters
    ----------
    explainer:
        SHAP TreeExplainer for the XGBoost model.

    processed_data:
        Patient data after preprocessing.

    feature_names:
        Feature names generated by the fitted
        ColumnTransformer.

    original_patient_data:
        Original patient DataFrame.

    top_n:
        Number of top contributing features to return.
    """

    # -----------------------------------------------------
    # Calculate SHAP values
    # -----------------------------------------------------

    shap_output = explainer(processed_data)

    shap_values = shap_output.values[0]

    # -----------------------------------------------------
    # Rank features by absolute SHAP impact
    # -----------------------------------------------------

    ranked_indices = np.argsort(
        np.abs(shap_values)
    )[::-1]

    explanations = []

    # -----------------------------------------------------
    # Build explanation objects
    # -----------------------------------------------------

    for index in ranked_indices[:top_n]:

        feature_name = feature_names[index]

        shap_value = float(
            shap_values[index]
        )

        # Determine whether this feature
        # pushes the prediction toward readmission.
        if shap_value > 0:
            direction = "increases_risk"
        else:
            direction = "decreases_risk"

        # -------------------------------------------------
        # Determine original feature name
        # -------------------------------------------------

        clean_feature_name = feature_name

        if "__" in clean_feature_name:
            clean_feature_name = clean_feature_name.split(
                "__",
                1
            )[1]

        # -------------------------------------------------
        # Find original patient value
        # -------------------------------------------------

        value = "N/A"

        if clean_feature_name in original_patient_data.columns:

            value = str(
                original_patient_data.iloc[0][
                    clean_feature_name
                ]
            )

        else:

            # Handle one-hot encoded features such as:
            #
            # Gender_Male
            # Smoking_Status_Never
            #
            # by finding the original column.

            for column in original_patient_data.columns:

                if clean_feature_name.startswith(
                    f"{column}_"
                ):

                    value = str(
                        original_patient_data.iloc[0][column]
                    )

                    break

        explanations.append(
            {
                "feature": clean_feature_name,
                "value": value,
                "shap_value": shap_value,
                "direction": direction,
            }
        )

    return explanations